version: '3.1'

services:
  # Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: fG4Lsk8daG2i
      MYSQL_ROOT_PASSWORD: k8daG2ifG4Ls
    volumes:
      - db:/var/lib/mysql
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: fG4Lsk8daG2i
      MYSQL_ROOT_PASSWORD: k8daG2ifG4Ls
    networks:
      - wpsite
  # Wordpress
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: fG4Lsk8daG2i
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpsite
  # sftp 
  sftp:
    image: atmoz/sftp
    volumes:
      - wordpress:/home/sftpuser/wordpress
    ports:
      - "2222:22"
    command: sftpuser:Osmosis.123:1001
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  wordpress:
  db:
